export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      // Add your table definitions here as they are in your Supabase project
      // Example: profiles table
      profiles: {
        Row: {
          id: string; // uuid, primary key, references auth.users.id
          updated_at: string | null;
          username: string | null;
          full_name: string | null;
          avatar_url: string | null;
          website: string | null;
        };
        Insert: {
          id: string; // uuid
          updated_at?: string | null;
          username?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          website?: string | null;
        };
        Update: {
          id?: string; // uuid
          updated_at?: string | null;
          username?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          website?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      // Example: inventory_items table (adjust to your actual schema)
      inventory_items: {
        Row: {
          id: string; // uuid, primary key
          created_at: string;
          name: string;
          sku: string;
          unit_price: number;
          quantity: number;
          vendor: string | null;
          category: string | null;
          user_id: string; // foreign key to auth.users.id
        };
        Insert: {
          id?: string; // uuid, defaults to gen_random_uuid()
          created_at?: string;
          name: string;
          sku: string;
          unit_price: number;
          quantity: number;
          vendor?: string | null;
          category?: string | null;
          user_id: string;
        };
        Update: {
          id?: string;
          created_at?: string;
          name?: string;
          sku?: string;
          unit_price?: number;
          quantity?: number;
          vendor?: string | null;
          category?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "inventory_items_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      // Add other tables like clients, invoices, expenses etc.
      // following the same structure. This file should be generated by:
      // npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts
    };
    Views: {
      // Add your view definitions here
    };
    Functions: {
      // Add your PostgreSQL function definitions here
    };
    Enums: {
      // Add your enum definitions here
    };
    CompositeTypes: {
      // Add your composite type definitions here
    };
  };
}

// Helper type to extract Row types from the Database interface
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Inserts<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type Updates<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// This is a placeholder. You should generate this file using the Supabase CLI.
// Run the command: `npx supabase gen types typescript --project-id <your-project-id> --schema public > src/types/supabase.ts`
// Make sure to replace `<your-project-id>` with your actual Supabase project ID.
// The `package.json` includes a script `supabase:types` for this. 